### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by philip-zakharov** [philip-zakharov/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by not-philip** [comment]
I'm a loyal and caring man who is protective and loving towards my family. Loyal to my friends, I value friendship almost as much as family. Boss and patriarch of the Corleone family. If you’re reading this you know what I do.
